Feature/add bll layer
Finka95/KM pull request #21
Opened 2024-06-25 14:28 UTC by Mmishaaa

* Add SubscriptionService
* Add mapster for mapping
* Update the Service Repository a bit

2024-06-25 14:32 UTC, moltenessence requested changes

2024-06-25 14:32 UTC, moltenessence commented on SubscriptionService/SubscriptionService.BLL/Services/SubscriptionService.cs
> +                UpdatedAt = DateTime.Now,
create _dateTime provider

2024-06-25 14:32 UTC, moltenessence commented on SubscriptionService/SubscriptionService.BLL/Services/SubscriptionService.cs
> +                ExpiresAt = DateTime.Now.AddMonths(1)
same

2024-06-25 14:32 UTC, moltenessence commented on SubscriptionService/SubscriptionService.BLL/Services/SubscriptionService.cs
> +        public async Task<Subscription> UpdateAsync(Guid id, SubscriptionType subscriptionType, CancellationToken cancellationToken)
formatting

2024-06-25 14:32 UTC, moltenessence commented on SubscriptionService/SubscriptionService.BLL/Services/SubscriptionService.cs
> +            subscriptionToUpdate.UpdatedAt = DateTime.Now;
provider

2024-06-26 07:18 UTC, moltenessence approved these changes

2024-06-26 11:57 UTC, DarPers approved these changes

2024-06-26 12:21 UTC, VadimZharikov approved these changes

2024-06-26 12:26 UTC, merged